package com.fxd927.mekanismgeneticengineering.common.registries;

import com.fxd927.mekanismgeneticengineering.common.MGEChemicalConstants;
import com.fxd927.mekanismgeneticengineering.common.MekanismGeneticEngineering;
import mekanism.api.chemical.Chemical;
import mekanism.common.registration.impl.ChemicalDeferredRegister;
import mekanism.common.registration.impl.DeferredChemical;

public class MGEChemicals {

    private MGEChemicals(){
    }

    public static final ChemicalDeferredRegister CHEMICALS = new ChemicalDeferredRegister(MekanismGeneticEngineering.MODID);

    public static final DeferredChemical<Chemical> METHANE;
    public static final DeferredChemical<Chemical> CHLOROFORM;
    public static final DeferredChemical<Chemical> PHENOL;

    public static final DeferredChemical<Chemical> ALLAY_DNA;
    public static final DeferredChemical<Chemical> ARMADILLO_DNA;
    public static final DeferredChemical<Chemical> AXOLOTL_DNA;
    public static final DeferredChemical<Chemical> BAT_DNA;
    public static final DeferredChemical<Chemical> BEE_DNA;
    public static final DeferredChemical<Chemical> BLAZE_DNA;
    public static final DeferredChemical<Chemical> BOGGED_DNA;
    public static final DeferredChemical<Chemical> BREEZE_DNA;
    public static final DeferredChemical<Chemical> CAMEL_DNA;
    public static final DeferredChemical<Chemical> CAT_DNA;
    public static final DeferredChemical<Chemical> CAVE_SPIDER_DNA;
    public static final DeferredChemical<Chemical> CHICKEN_DNA;
    public static final DeferredChemical<Chemical> COD_DNA;
    public static final DeferredChemical<Chemical> COW_DNA;
    public static final DeferredChemical<Chemical> CREEPER_DNA;
    public static final DeferredChemical<Chemical> DOLPHIN_DNA;
    public static final DeferredChemical<Chemical> DONKEY_DNA;
    public static final DeferredChemical<Chemical> DROWNED_DNA;
    public static final DeferredChemical<Chemical> ELDER_GUARDIAN_DNA;
    public static final DeferredChemical<Chemical> ENDER_DRAGON_DNA;
    public static final DeferredChemical<Chemical> ENDERMAN_DNA;
    public static final DeferredChemical<Chemical> ENDERMITE_DNA;
    public static final DeferredChemical<Chemical> EVOKER_DNA;
    public static final DeferredChemical<Chemical> FOX_DNA;
    public static final DeferredChemical<Chemical> FROG_DNA;
    public static final DeferredChemical<Chemical> GHAST_DNA;
    public static final DeferredChemical<Chemical> GLOW_SQUID_DNA;
    public static final DeferredChemical<Chemical> GOAT_DNA;
    public static final DeferredChemical<Chemical> GUARDIAN_DNA;
    public static final DeferredChemical<Chemical> LLAMA_DNA;
    public static final DeferredChemical<Chemical> HOGLIN_DNA;
    public static final DeferredChemical<Chemical> HORSE_DNA;
    public static final DeferredChemical<Chemical> HUSK_DNA;
    public static final DeferredChemical<Chemical> MAGMA_CUBE_DNA;
    public static final DeferredChemical<Chemical> MOOSHROOM_DNA;
    public static final DeferredChemical<Chemical> MULE_DNA;
    public static final DeferredChemical<Chemical> OCELOT_DNA;
    public static final DeferredChemical<Chemical> PANDA_DNA;
    public static final DeferredChemical<Chemical> PARROT_DNA;
    public static final DeferredChemical<Chemical> PHANTOM_DNA;
    public static final DeferredChemical<Chemical> PIG_DNA;
    public static final DeferredChemical<Chemical> PIGLIN_DNA;
    public static final DeferredChemical<Chemical> PILLAGER_DNA;
    public static final DeferredChemical<Chemical> POLAR_BEAR_DNA;
    public static final DeferredChemical<Chemical> PUFFERFISH_DNA;
    public static final DeferredChemical<Chemical> RABBIT_DNA;
    public static final DeferredChemical<Chemical> RAVAGER_DNA;
    public static final DeferredChemical<Chemical> SALMON_DNA;
    public static final DeferredChemical<Chemical> SHEEP_DNA;
    public static final DeferredChemical<Chemical> SHULKER_DNA;
    public static final DeferredChemical<Chemical> SILVERFISH_DNA;
    public static final DeferredChemical<Chemical> SKELETON_DNA;
    public static final DeferredChemical<Chemical> SLIME_DNA;
    public static final DeferredChemical<Chemical> SNIFFER_DNA;
    public static final DeferredChemical<Chemical> SPIDER_DNA;
    public static final DeferredChemical<Chemical> SQUID_DNA;
    public static final DeferredChemical<Chemical> STRAY_DNA;
    public static final DeferredChemical<Chemical> STRIDER_DNA;
    public static final DeferredChemical<Chemical> TROPICAL_FISH_DNA;
    public static final DeferredChemical<Chemical> TURTLE_DNA;
    public static final DeferredChemical<Chemical> VEX_DNA;
    public static final DeferredChemical<Chemical> VILLAGER_DNA;
    public static final DeferredChemical<Chemical> VINDICATOR_DNA;
    public static final DeferredChemical<Chemical> WARDEN_DNA;
    public static final DeferredChemical<Chemical> WITCH_DNA;
    public static final DeferredChemical<Chemical> WITHER_DNA;
    public static final DeferredChemical<Chemical> WITHER_SKELETON_DNA;
    public static final DeferredChemical<Chemical> WOLF_DNA;
    public static final DeferredChemical<Chemical> ZOGLIN_DNA;
    public static final DeferredChemical<Chemical> ZOMBIE_DNA;
    public static final DeferredChemical<Chemical> ZOMBIE_VILLAGER_DNA;
    public static final DeferredChemical<Chemical> ZOMBIFIED_PIGLIN_DNA;

    public static final DeferredChemical<Chemical> BUG_GENE;
    public static final DeferredChemical<Chemical> COLD_RESISTANCE_GENE;
    public static final DeferredChemical<Chemical> COLORFUL_GENE;
    public static final DeferredChemical<Chemical> EVILNESS_GENE;
    public static final DeferredChemical<Chemical> FLIGHT_GENE;
    public static final DeferredChemical<Chemical> GENERAL_ENVIRONMENTAL_COMPATIBILITY_GENE;
    public static final DeferredChemical<Chemical> HARDNESS_GENE;
    public static final DeferredChemical<Chemical> HEARING_GENE;
    public static final DeferredChemical<Chemical> HOT_RESISTANCE_GENE;
    public static final DeferredChemical<Chemical> INTELLIGENCE_GENE;
    public static final DeferredChemical<Chemical> JUMPING_GENE;
    public static final DeferredChemical<Chemical> MILK_PRODUCTION_DNA;
    public static final DeferredChemical<Chemical> MULTIPLICATION_GENE;
    public static final DeferredChemical<Chemical> NIGHT_VISION_GENE;
    public static final DeferredChemical<Chemical> OVIPAROUS_GENE;
    public static final DeferredChemical<Chemical> SMELL_GENE;
    public static final DeferredChemical<Chemical> SOFT_BODY_GENE;
    public static final DeferredChemical<Chemical> SPATIAL_AWARENESS_GENE;
    public static final DeferredChemical<Chemical> SPEED_GENE;
    public static final DeferredChemical<Chemical> TRANSPORTATION_GENE;
    public static final DeferredChemical<Chemical> UNDEAD_GENE;
    public static final DeferredChemical<Chemical> UNDERWATER_ADAPTATION_GENE;
    public static final DeferredChemical<Chemical> USING_EFFECT_GENE;




    static {
        METHANE = CHEMICALS.register(MGEChemicalConstants.METHANE);
        CHLOROFORM = CHEMICALS.register(MGEChemicalConstants.CHLOROFORM);
        PHENOL = CHEMICALS.register(MGEChemicalConstants.PHENOL);

        ALLAY_DNA = CHEMICALS.register("allay_dna", 0xFEEF9C);
        ARMADILLO_DNA = CHEMICALS.register("armadillo_dna", 0xFEEF9C);
        AXOLOTL_DNA = CHEMICALS.register("axolotl_dna", 0xFEEF9C);
        BAT_DNA = CHEMICALS.register("bat_dna", 0xFEEF9C);
        BEE_DNA = CHEMICALS.register("bee_dna", 0xFEEF9C);
        BLAZE_DNA = CHEMICALS.register("blaze_dna", 0xFEEF9C);
        BOGGED_DNA = CHEMICALS.register("bogged_dna", 0xFEEF9C);
        BREEZE_DNA = CHEMICALS.register("breeze_dna", 0xFEEF9C);
        CAMEL_DNA = CHEMICALS.register("camel_dna", 0xFEEF9C);
        CAT_DNA = CHEMICALS.register("cat_dna", 0xFEEF9C);
        CAVE_SPIDER_DNA = CHEMICALS.register("cave_spider_dna", 0xFEEF9C);
        CHICKEN_DNA = CHEMICALS.register("chicken_dna", 0xFEEF9C);
        COD_DNA = CHEMICALS.register("cod_dna", 0xFEEF9C);
        COW_DNA = CHEMICALS.register("cow_dna", 0xFEEF9C);
        CREEPER_DNA = CHEMICALS.register("creeper_dna", 0xFEEF9C);
        DOLPHIN_DNA = CHEMICALS.register("dolphin_dna", 0xFEEF9C);
        DONKEY_DNA = CHEMICALS.register("donkey_dna", 0xFEEF9C);
        DROWNED_DNA = CHEMICALS.register("drowned_dna", 0xFEEF9C);
        ELDER_GUARDIAN_DNA = CHEMICALS.register("elder_guardian_dna", 0xFEEF9C);
        ENDER_DRAGON_DNA = CHEMICALS.register("ender_dragon_dna", 0xFEEF9C);
        ENDERMAN_DNA = CHEMICALS.register("enderman_dna", 0xFEEF9C);
        ENDERMITE_DNA = CHEMICALS.register("endermite_dna", 0xFEEF9C);
        EVOKER_DNA = CHEMICALS.register("evoker_dna", 0xFEEF9C);
        FOX_DNA = CHEMICALS.register("fox_dna", 0xFEEF9C);
        FROG_DNA = CHEMICALS.register("frog_dna", 0xFEEF9C);
        GHAST_DNA = CHEMICALS.register("ghast_dna", 0xFEEF9C);
        GLOW_SQUID_DNA = CHEMICALS.register("glow_squid_dna", 0xFEEF9C);
        GOAT_DNA = CHEMICALS.register("goat_dna", 0xFEEF9C);
        GUARDIAN_DNA = CHEMICALS.register("guardian_dna", 0xFEEF9C);
        HOGLIN_DNA = CHEMICALS.register("hoglin_dna", 0xFEEF9C);
        HORSE_DNA = CHEMICALS.register("horse_dna", 0xFEEF9C);
        HUSK_DNA = CHEMICALS.register("husk_dna", 0xFEEF9C);
        LLAMA_DNA = CHEMICALS.register("llama_dna", 0xFEEF9C);
        MAGMA_CUBE_DNA = CHEMICALS.register("magma_cube_dna", 0xFEEF9C);
        MOOSHROOM_DNA = CHEMICALS.register("mooshroom_dna", 0xFEEF9C);
        MULE_DNA = CHEMICALS.register("mule_dna", 0xFEEF9C);
        OCELOT_DNA = CHEMICALS.register("ocelot_dna", 0xFEEF9C);
        PANDA_DNA = CHEMICALS.register("panda_dna",0xFEEF9C);
        PARROT_DNA = CHEMICALS.register("parrot_dna",0xFEEF9C);
        PHANTOM_DNA = CHEMICALS.register("phantom_dna", 0xFEEF9C);
        PIG_DNA = CHEMICALS.register("pig_dna", 0xFEEF9C);
        PIGLIN_DNA = CHEMICALS.register("piglin_dna", 0xFEEF9C);
        PILLAGER_DNA = CHEMICALS.register("pillager_dna", 0xFEEF9C);
        POLAR_BEAR_DNA = CHEMICALS.register("polar_bear_dna", 0xFEEF9C);
        PUFFERFISH_DNA = CHEMICALS.register("pufferfish_dna", 0xFEEF9C);
        RABBIT_DNA = CHEMICALS.register("rabbit_dna", 0xFEEF9C);
        RAVAGER_DNA = CHEMICALS.register("ravager_dna", 0xFEEF9C);
        SALMON_DNA = CHEMICALS.register("salmon_dna", 0xFEEF9C);
        SHEEP_DNA = CHEMICALS.register("sheep_dna", 0xFEEF9C);
        SHULKER_DNA = CHEMICALS.register("shulker_dna", 0xFEEF9C);
        SILVERFISH_DNA = CHEMICALS.register("silverfish_dna", 0xFEEF9C);
        SKELETON_DNA = CHEMICALS.register("skeleton_dna", 0xFEEF9C);
        SLIME_DNA = CHEMICALS.register("slime_dna", 0xFEEF9C);
        SNIFFER_DNA = CHEMICALS.register("sniffer_dna", 0xFEEF9C);
        SPIDER_DNA = CHEMICALS.register("spider_dna", 0xFEEF9C);
        SQUID_DNA = CHEMICALS.register("squid_dna", 0xFEEF9C);
        STRAY_DNA = CHEMICALS.register("stray_dna", 0xFEEF9C);
        STRIDER_DNA = CHEMICALS.register("strider_dna", 0xFEEF9C);
        TROPICAL_FISH_DNA = CHEMICALS.register("tropical_fish_dna", 0xFEEF9C);
        TURTLE_DNA = CHEMICALS.register("turtle_dna", 0xFEEF9C);
        VEX_DNA = CHEMICALS.register("vex_dna", 0xFEEF9C);
        VILLAGER_DNA = CHEMICALS.register("villager_dna", 0xFEEF9C);
        VINDICATOR_DNA = CHEMICALS.register("vindicator_dna", 0xFEEF9C);
        WARDEN_DNA = CHEMICALS.register("warden_dna", 0xFEEF9C);
        WITCH_DNA = CHEMICALS.register("witch_dna", 0xFEEF9C);
        WITHER_DNA = CHEMICALS.register("wither_dna", 0xFEEF9C);
        WITHER_SKELETON_DNA = CHEMICALS.register("wither_skeleton_dna", 0xFEEF9C);
        WOLF_DNA = CHEMICALS.register("wolf_dna", 0xFEEF9C);
        ZOGLIN_DNA = CHEMICALS.register("zoglin_dna", 0xFEEF9C);
        ZOMBIE_DNA = CHEMICALS.register("zombie_dna", 0xFEEF9C);
        ZOMBIE_VILLAGER_DNA = CHEMICALS.register("zombie_villager_dna", 0xFEEF9C);
        ZOMBIFIED_PIGLIN_DNA = CHEMICALS.register("zombified_piglin_dna", 0xFEEF9C);

        BUG_GENE = CHEMICALS.register("bug_gene", 0xA8C093);
        COLD_RESISTANCE_GENE = CHEMICALS.register("cold_resistance_gene", 0xC0FAFF);
        COLORFUL_GENE = CHEMICALS.register("colorful_gene", 0xFFED3F);
        EVILNESS_GENE = CHEMICALS.register("evilness_gene", 0x3A371E);
        FLIGHT_GENE = CHEMICALS.register("flight_gene", 0x6CF6FF);
        GENERAL_ENVIRONMENTAL_COMPATIBILITY_GENE = CHEMICALS.register("general_environmental_compatibility_gene", 0xFFC366);
        HARDNESS_GENE = CHEMICALS.register("hardness_gene", 0x6490DC);
        HEARING_GENE = CHEMICALS.register("hearing_gene", 0xFF80E6);
        HOT_RESISTANCE_GENE = CHEMICALS.register("hot_resistance_gene", 0xFC6A6A);
        INTELLIGENCE_GENE = CHEMICALS.register("intelligence_gene", 0x8A50FF);
        JUMPING_GENE = CHEMICALS.register("jumping_gene", 0x55FF00);
        MILK_PRODUCTION_DNA = CHEMICALS.register("milk_production_gene", 0xFFFFFF);
        MULTIPLICATION_GENE = CHEMICALS.register("multiplication_gene", 0x3737FF);
        NIGHT_VISION_GENE = CHEMICALS.register("night_vision_gene", 0x6161FF);
        OVIPAROUS_GENE = CHEMICALS.register("oviparous_gene", 0xB3E5BA);
        SMELL_GENE = CHEMICALS.register("smell_gene", 0xFAFF4D);
        SOFT_BODY_GENE = CHEMICALS.register("soft_body_gene", 0x5CBCE5);
        SPATIAL_AWARENESS_GENE = CHEMICALS.register("spatial_awareness_gene", 0x8A43E6);
        SPEED_GENE = CHEMICALS.register("speed_gene", 0x5FD4F7);
        TRANSPORTATION_GENE = CHEMICALS.register("transportation_gene", 0x94758E);
        UNDEAD_GENE = CHEMICALS.register("undead_gene", 0x566255);
        UNDERWATER_ADAPTATION_GENE = CHEMICALS.register("underwater_adaptation_gene", 0x406BFA);
        USING_EFFECT_GENE = CHEMICALS.register("using_effect_gene", 0xFF9A00);
    }
}

