package com.fxd927.mekanismgeneticengineering.common.datagen.providers;

import com.fxd927.mekanismgeneticengineering.common.MekanismGeneticEngineering;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class LanguageGenerator extends LanguageProvider {

    public LanguageGenerator(PackOutput packOutput) {
        super(packOutput, MekanismGeneticEngineering.MODID, "en_us");
    }

    @Override
    protected void addTranslations() {
        add("block.mekanismgeneticengineering.drops_reproducer", "Drops Reproducer");
        add("block.mekanismgeneticengineering.gene_analyzer", "Gene Analyzer");
        add("block.mekanismgeneticengineering.nuclear_acid_centrifuge", "Nuclear Acid Centrifuge");
        add("block.mekanismgeneticengineering.structural_restoration_synthesis_machine", "Structural Restoration Synthesis Machine");
        add("chemical.mekanismgeneticengineering.methane", "Methane");
        add("chemical.mekanismgeneticengineering.chloroform", "Chloroform");
        add("chemical.mekanismgeneticengineering.phenol", "Phenol");
        add("chemical.mekanismgeneticengineering.allay_dna", "Allay DNA");
        add("chemical.mekanismgeneticengineering.armadillo_dna", "Armadillo DNA");
        add("chemical.mekanismgeneticengineering.axolotl_dna", "Axolotl DNA");
        add("chemical.mekanismgeneticengineering.bat_dna", "Bat DNA");
        add("chemical.mekanismgeneticengineering.bee_dna", "Bee DNA");
        add("chemical.mekanismgeneticengineering.blaze_dna", "Blaze DNA");
        add("chemical.mekanismgeneticengineering.bogged_dna", "Bogged DNA");
        add("chemical.mekanismgeneticengineering.breeze_dna", "Breeze DNA");
        add("chemical.mekanismgeneticengineering.camel_dna", "Camel DNA");
        add("chemical.mekanismgeneticengineering.cat_dna", "Cat DNA");
        add("chemical.mekanismgeneticengineering.cave_spider_dna", "Cave Spider DNA");
        add("chemical.mekanismgeneticengineering.chicken_dna", "Chicken DNA");
        add("chemical.mekanismgeneticengineering.cod_dna", "Cod DNA");
        add("chemical.mekanismgeneticengineering.cow_dna", "Cow DNA");
        add("chemical.mekanismgeneticengineering.creeper_dna", "Creeper DNA");
        add("chemical.mekanismgeneticengineering.dolphin_dna", "Dolphin DNA");
        add("chemical.mekanismgeneticengineering.donkey_dna", "Donkey DNA");
        add("chemical.mekanismgeneticengineering.drowned_dna", "Drowned DNA");
        add("chemical.mekanismgeneticengineering.elder_guardian_dna", "Elder Guardian DNA");
        add("chemical.mekanismgeneticengineering.ender_dragon_dna", "Ender Dragon DNA");
        add("chemical.mekanismgeneticengineering.enderman_dna", "Enderman DNA");
        add("chemical.mekanismgeneticengineering.endermite_dna", "Endermite DNA");
        add("chemical.mekanismgeneticengineering.evoker_dna", "Evoker DNA");
        add("chemical.mekanismgeneticengineering.fox_dna", "Fox DNA");
        add("chemical.mekanismgeneticengineering.frog_dna", "Frog DNA");
        add("chemical.mekanismgeneticengineering.ghast_dna", "Ghast DNA");
        add("chemical.mekanismgeneticengineering.glow_squid_dna", "Glow Squid DNA");
        add("chemical.mekanismgeneticengineering.goat_dna", "Goat DNA");
        add("chemical.mekanismgeneticengineering.guardian_dna", "Guardian DNA");
        add("chemical.mekanismgeneticengineering.hoglin_dna", "Hoglin DNA");
        add("chemical.mekanismgeneticengineering.horse_dna", "Horse DNA");
        add("chemical.mekanismgeneticengineering.husk_dna", "Husk DNA");
        add("chemical.mekanismgeneticengineering.llama_dna", "Llama DNA");
        add("chemical.mekanismgeneticengineering.magma_cube_dna", "Magma Cube DNA");
        add("chemical.mekanismgeneticengineering.mooshroom_dna", "Mooshroom DNA");
        add("chemical.mekanismgeneticengineering.mule_dna", "Mule DNA");
        add("chemical.mekanismgeneticengineering.ocelot_dna", "Ocelot DNA");
        add("chemical.mekanismgeneticengineering.panda_dna", "Panda DNA");
        add("chemical.mekanismgeneticengineering.parrot_dna", "Parrot DNA");
        add("chemical.mekanismgeneticengineering.phantom_dna", "Phantom DNA");
        add("chemical.mekanismgeneticengineering.pig_dna", "Pig DNA");
        add("chemical.mekanismgeneticengineering.piglin_dna", "Piglin DNA");
        add("chemical.mekanismgeneticengineering.pillager_dna", "Pillager DNA");
        add("chemical.mekanismgeneticengineering.polar_bear_dna", "Polar Bear DNA");
        add("chemical.mekanismgeneticengineering.pufferfish_dna", "Pufferfish DNA");
        add("chemical.mekanismgeneticengineering.rabbit_dna", "Rabbit DNA");
        add("chemical.mekanismgeneticengineering.ravager_dna", "Ravager DNA");
        add("chemical.mekanismgeneticengineering.salmon_dna", "Salmon DNA");
        add("chemical.mekanismgeneticengineering.sheep_dna", "Sheep DNA");
        add("chemical.mekanismgeneticengineering.shulker_dna", "Shulker DNA");
        add("chemical.mekanismgeneticengineering.silverfish_dna", "Silverfish DNA");
        add("chemical.mekanismgeneticengineering.skeleton_dna", "Skeleton DNA");
        add("chemical.mekanismgeneticengineering.slime_dna", "Slime DNA");
        add("chemical.mekanismgeneticengineering.sniffer_dna", "Sniffer DNA");
        add("chemical.mekanismgeneticengineering.spider_dna", "Spider DNA");
        add("chemical.mekanismgeneticengineering.squid_dna", "Squid DNA");
        add("chemical.mekanismgeneticengineering.stray_dna", "Stray DNA");
        add("chemical.mekanismgeneticengineering.strider_dna", "Strider DNA");
        add("chemical.mekanismgeneticengineering.tropical_fish_dna", "Tropical Fish DNA");
        add("chemical.mekanismgeneticengineering.turtle_dna", "Turtle DNA");
        add("chemical.mekanismgeneticengineering.vex_dna", "Vex DNA");
        add("chemical.mekanismgeneticengineering.villager_dna", "Villager DNA");
        add("chemical.mekanismgeneticengineering.vindicator_dna", "Vindicator DNA");
        add("chemical.mekanismgeneticengineering.warden_dna", "Warden DNA");
        add("chemical.mekanismgeneticengineering.witch_dna", "Witch DNA");
        add("chemical.mekanismgeneticengineering.wither_dna", "Wither DNA");
        add("chemical.mekanismgeneticengineering.wither_skeleton_dna", "Wither Skeleton DNA");
        add("chemical.mekanismgeneticengineering.wolf_dna", "Wolf DNA");
        add("chemical.mekanismgeneticengineering.zoglin_dna", "Zoglin DNA");
        add("chemical.mekanismgeneticengineering.zombie_dna", "Zombie DNA");
        add("chemical.mekanismgeneticengineering.zombie_villager_dna", "Zombie Villager DNA");
        add("chemical.mekanismgeneticengineering.zombified_piglin_dna", "Zombified Piglin DNA");
        add("chemical.mekanismgeneticengineering.bug_gene", "Bug Gene");
        add("chemical.mekanismgeneticengineering.cold_resistance_gene", "Cold Resistance Gene");
        add("chemical.mekanismgeneticengineering.colorful_gene", "Colorful Gene");
        add("chemical.mekanismgeneticengineering.evilness_gene", "Evilness Gene");
        add("chemical.mekanismgeneticengineering.flight_gene", "Flight Gene");
        add("chemical.mekanismgeneticengineering.general_environmental_compatibility_gene", "General Environmental Compatibility Gene");
        add("chemical.mekanismgeneticengineering.hardness_gene", "Hardness Gene");
        add("chemical.mekanismgeneticengineering.hearing_gene", "Hearing Gene");
        add("chemical.mekanismgeneticengineering.hot_resistance_gene", "Hot Resistance Gene");
        add("chemical.mekanismgeneticengineering.intelligence_gene", "Intelligence Gene");
        add("chemical.mekanismgeneticengineering.jumping_gene", "Jumping Gene");
        add("chemical.mekanismgeneticengineering.milk_production_gene", "Milk Production Gene");
        add("chemical.mekanismgeneticengineering.multiplication_gene", "Multiplication Gene");
        add("chemical.mekanismgeneticengineering.night_vision_gene", "Night Vision Gene");
        add("chemical.mekanismgeneticengineering.oviparous_gene", "Oviparous Gene");
        add("chemical.mekanismgeneticengineering.smell_gene", "Smell Gene");
        add("chemical.mekanismgeneticengineering.soft_body_gene", "Soft Body Gene");
        add("chemical.mekanismgeneticengineering.spatial_awareness_gene", "Spatial Awareness Gene");
        add("chemical.mekanismgeneticengineering.speed_gene", "Speed Gene");
        add("chemical.mekanismgeneticengineering.transportation_gene", "Transportation Gene");
        add("chemical.mekanismgeneticengineering.the_end_gene", "The End Gene");
        add("chemical.mekanismgeneticengineering.undead_gene", "Undead Gene");
        add("chemical.mekanismgeneticengineering.underwater_adaptation_gene", "Underwater Adaptation Gene");
        add("chemical.mekanismgeneticengineering.using_effect_gene", "Using Effect Gene");
        add("chemical.mekanismgeneticengineering.wither_gene", "Wither Gene");
        add("constants.mekanismgeneticengineering.mod_name", "Mekanism Genetic Engineering");
        add("container.mekanismgeneticengineering.drops_reproducer", "Drops Reproducer");
        add("container.mekanismgeneticengineering.gene_analyzer", "Gene Analyzer");
        add("container.mekanismgeneticengineering.nuclear_acid_centrifuge", "Nuclear Acid Centrifuge");
        add("container.mekanismgeneticengineering.structural_restoration_synthesis_machine", "Structural Restoration Synthesis Machine");
        add("description.mekanismgeneticengineering.gene_analyzer", "This machine can analyze DNA and extract specific genes.");
        add("description.mekanismgeneticengineering.nuclear_acid_centrifuge", "");
        add("item.mekanismgeneticengineering.coal_tar", "Coal Tar");
        add("item.mekanismgeneticengineering.chloroform_bucket", "Chloroform Bucket");
        add("item.mekanismgeneticengineering.methane_bucket", "Methane Bucket");
        add("item.mekanismgeneticengineering.phenol_bucket", "Phenol Bucket");
        add("item.mekanismgeneticengineering.syringe", "Syringe");
    }

    public static class JAJP extends LanguageProvider {
        public JAJP(PackOutput packOutput) {
            super(packOutput, MekanismGeneticEngineering.MODID, "ja_jp");
        }

        @Override
        protected void addTranslations() {
            add("block.mekanismgeneticengineering.drops_reproducer", "ドロップ生成機");
            add("block.mekanismgeneticengineering.gene_analyzer", "遺伝子解析装置");
            add("block.mekanismgeneticengineering.nuclear_acid_centrifuge", "核酸遠心分離機");
            add("block.mekanismgeneticengineering.structural_restoration_synthesis_machine", "構造修復合成機");
            add("chemical.mekanismgeneticengineering.methane", "メタン");
            add("chemical.mekanismgeneticengineering.chloroform", "クロロホルム");
            add("chemical.mekanismgeneticengineering.phenol", "フェノール");
            add("chemical.mekanismgeneticengineering.allay_dna", "アレイのDNA");
            add("chemical.mekanismgeneticengineering.armadillo_dna", "アルマジロのDNA");
            add("chemical.mekanismgeneticengineering.axolotl_dna", "ウーパールーパーのDNA");
            add("chemical.mekanismgeneticengineering.bat_dna", "コウモリのDNA");
            add("chemical.mekanismgeneticengineering.bee_dna", "ミツバチのDNA");
            add("chemical.mekanismgeneticengineering.blaze_dna", "ブレイズのDNA");
            add("chemical.mekanismgeneticengineering.bogged_dna", "ボグドのDNA");
            add("chemical.mekanismgeneticengineering.breeze_dna", "ブリーズのDNA");
            add("chemical.mekanismgeneticengineering.camel_dna", "ラクダのDNA");
            add("chemical.mekanismgeneticengineering.cat_dna", "ネコのDNA");
            add("chemical.mekanismgeneticengineering.cave_spider_dna", "洞窟グモのDNA");
            add("chemical.mekanismgeneticengineering.chicken_dna", "ニワトリのDNA");
            add("chemical.mekanismgeneticengineering.cod_dna", "タラのDNA");
            add("chemical.mekanismgeneticengineering.cow_dna", "ウシのDNA");
            add("chemical.mekanismgeneticengineering.creeper_dna", "クリーパーのDNA");
            add("chemical.mekanismgeneticengineering.dolphin_dna", "イルカのDNA");
            add("chemical.mekanismgeneticengineering.donkey_dna", "ロバのDNA");
            add("chemical.mekanismgeneticengineering.drowned_dna", "ドラウンドのDNA");
            add("chemical.mekanismgeneticengineering.elder_guardian_dna", "エルダーガーディアンのDNA");
            add("chemical.mekanismgeneticengineering.ender_dragon_dna", "エンダードラゴンのDNA");
            add("chemical.mekanismgeneticengineering.enderman_dna", "エンダーマンのDNA");
            add("chemical.mekanismgeneticengineering.endermite_dna", "エンダーマイトのDNA");
            add("chemical.mekanismgeneticengineering.evoker_dna", "エヴォーカーのDNA");
            add("chemical.mekanismgeneticengineering.fox_dna", "キツネのDNA");
            add("chemical.mekanismgeneticengineering.frog_dna", "カエルのDNA");
            add("chemical.mekanismgeneticengineering.ghast_dna", "ガストのDNA");
            add("chemical.mekanismgeneticengineering.glow_squid_dna", "ヒカリイカのDNA");
            add("chemical.mekanismgeneticengineering.goat_dna", "ヤギのDNA");
            add("chemical.mekanismgeneticengineering.guardian_dna", "ガーディアンのDNA");
            add("chemical.mekanismgeneticengineering.hoglin_dna", "ホグリンのDNA");
            add("chemical.mekanismgeneticengineering.horse_dna", "ウマのDNA");
            add("chemical.mekanismgeneticengineering.husk_dna", "ハスクのDNA");
            add("chemical.mekanismgeneticengineering.llama_dna", "ラマのDNA");
            add("chemical.mekanismgeneticengineering.magma_cube_dna", "マグマキューブのDNA");
            add("chemical.mekanismgeneticengineering.mooshroom_dna", "ムーシュルームのDNA");
            add("chemical.mekanismgeneticengineering.mule_dna", "ラバのDNA");
            add("chemical.mekanismgeneticengineering.ocelot_dna", "ヤマネコのDNA");
            add("chemical.mekanismgeneticengineering.panda_dna", "パンダのDNA");
            add("chemical.mekanismgeneticengineering.parrot_dna", "オウムのDNA");
            add("chemical.mekanismgeneticengineering.phantom_dna", "ファントムのDNA");
            add("chemical.mekanismgeneticengineering.pig_dna", "ブタのDNA");
            add("chemical.mekanismgeneticengineering.piglin_dna", "ピグリンのDNA");
            add("chemical.mekanismgeneticengineering.pillager_dna", "ピリジャーのDNA");
            add("chemical.mekanismgeneticengineering.polar_bear_dna", "シロクマのDNA");
            add("chemical.mekanismgeneticengineering.pufferfish_dna", "フグのDNA");
            add("chemical.mekanismgeneticengineering.rabbit_dna", "ウサギのDNA");
            add("chemical.mekanismgeneticengineering.ravager_dna", "ラヴェジャーのDNA");
            add("chemical.mekanismgeneticengineering.salmon_dna", "サケのDNA");
            add("chemical.mekanismgeneticengineering.sheep_dna", "ヒツジのDNA");
            add("chemical.mekanismgeneticengineering.shulker_dna", "シュルカーのDNA");
            add("chemical.mekanismgeneticengineering.silverfish_dna", "シルバーフィッシュのDNA");
            add("chemical.mekanismgeneticengineering.skeleton_dna", "スケルトンのDNA");
            add("chemical.mekanismgeneticengineering.slime_dna", "スライムのDNA");
            add("chemical.mekanismgeneticengineering.sniffer_dna", "スニッファーのDNA");
            add("chemical.mekanismgeneticengineering.spider_dna", "クモのDNA");
            add("chemical.mekanismgeneticengineering.squid_dna", "イカのDNA");
            add("chemical.mekanismgeneticengineering.stray_dna", "ストレイのDNA");
            add("chemical.mekanismgeneticengineering.strider_dna", "ストライダーのDNA");
            add("chemical.mekanismgeneticengineering.tropical_fish_dna", "熱帯魚のDNA");
            add("chemical.mekanismgeneticengineering.turtle_dna", "カメのDNA");
            add("chemical.mekanismgeneticengineering.vex_dna", "ヴェックスのDNA");
            add("chemical.mekanismgeneticengineering.villager_dna", "村人のDNA");
            add("chemical.mekanismgeneticengineering.vindicator_dna", "ヴィンディケーターのDNA");
            add("chemical.mekanismgeneticengineering.warden_dna", "ウォーデンのDNA");
            add("chemical.mekanismgeneticengineering.witch_dna", "ウィッチのDNA");
            add("chemical.mekanismgeneticengineering.wither_dna", "ウィザーのDNA");
            add("chemical.mekanismgeneticengineering.wither_skeleton_dna", "ウィザースケルトンのDNA");
            add("chemical.mekanismgeneticengineering.wolf_dna", "オオカミのDNA");
            add("chemical.mekanismgeneticengineering.zoglin_dna", "ゾグリンのDNA");
            add("chemical.mekanismgeneticengineering.zombie_dna", "ゾンビのDNA");
            add("chemical.mekanismgeneticengineering.zombie_villager_dna", "ゾンビ村人のDNA");
            add("chemical.mekanismgeneticengineering.zombified_piglin_dna", "ゾンビピグリンのDNA");
            add("chemical.mekanismgeneticengineering.bug_gene", "虫の遺伝子");
            add("chemical.mekanismgeneticengineering.cold_resistance_gene", "低温耐性の遺伝子");
            add("chemical.mekanismgeneticengineering.colorful_gene", "多彩の遺伝子");
            add("chemical.mekanismgeneticengineering.evilness_gene", "悪心の遺伝子");
            add("chemical.mekanismgeneticengineering.flight_gene", "飛行の遺伝子");
            add("chemical.mekanismgeneticengineering.general_environmental_compatibility_gene", "汎環境性の遺伝子");
            add("chemical.mekanismgeneticengineering.hardness_gene", "硬性の遺伝子");
            add("chemical.mekanismgeneticengineering.hearing_gene", "聴覚の遺伝子");
            add("chemical.mekanismgeneticengineering.hot_resistance_gene", "高温耐性の遺伝子");
            add("chemical.mekanismgeneticengineering.intelligence_gene", "知能の遺伝子");
            add("chemical.mekanismgeneticengineering.jumping_gene", "跳躍の遺伝子");
            add("chemical.mekanismgeneticengineering.milk_production_gene", "乳生産の遺伝子");
            add("chemical.mekanismgeneticengineering.multiplication_gene", "増殖の遺伝子");
            add("chemical.mekanismgeneticengineering.night_vision_gene", "暗視の遺伝子");
            add("chemical.mekanismgeneticengineering.oviparous_gene", "卵生の遺伝子");
            add("chemical.mekanismgeneticengineering.smell_gene", "嗅覚の遺伝子");
            add("chemical.mekanismgeneticengineering.soft_body_gene", "軟体の遺伝子");
            add("chemical.mekanismgeneticengineering.spatial_awareness_gene", "空間認識の遺伝子");
            add("chemical.mekanismgeneticengineering.speed_gene", "俊敏性の遺伝子");
            add("chemical.mekanismgeneticengineering.transportation_gene", "運搬の遺伝子");
            add("chemical.mekanismgeneticengineering.the_end_gene", "果ての遺伝子");
            add("chemical.mekanismgeneticengineering.undead_gene", "アンデッドの遺伝子");
            add("chemical.mekanismgeneticengineering.underwater_adaptation_gene", "水中適応の遺伝子");
            add("chemical.mekanismgeneticengineering.using_effect_gene", "エフェクト利用の遺伝子");
            add("chemical.mekanismgeneticengineering.wither_gene", "衰弱の遺伝子");
            add("constants.mekanismgeneticengineering.mod_name", "Mekanism Genetic Engineering");
            add("container.mekanismgeneticengineering.drops_reproducer", "ドロップ生成機");
            add("container.mekanismgeneticengineering.gene_analyzer", "遺伝子解析装置");
            add("container.mekanismgeneticengineering.nuclear_acid_centrifuge", "核酸遠心分離機");
            add("container.mekanismgeneticengineering.structural_restoration_synthesis_machine", "構造修復合成機");
            add("description.mekanismgeneticengineering.gene_analyzer", "遺伝子解析装置は、DNAを分析して遺伝子を抽出する装置です。");
            add("description.mekanismgeneticengineering.nuclear_acid_centrifuge", "核酸遠心分離機は、DNAを分離して純度を高める装置です。");
            add("item.mekanismgeneticengineering.coal_tar", "コールタール");
            add("item.mekanismgeneticengineering.chloroform_bucket", "クロロホルム入りのバケツ");
            add("item.mekanismgeneticengineering.methane_bucket", "メタン入りのバケツ");
            add("item.mekanismgeneticengineering.phenol_bucket", "フェノール入りのバケツ");
            add("item.mekanismgeneticengineering.syringe", "注射器");
        }
    }
}
